<a href="https://colab.research.google.com/github/JorgeZarama/Supervisado/blob/main/Programa1_Normalizacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import preprocessing
import numpy as np

In [ ]:
# Carga de datos.
X_train = np.array([[ 1., -4.,  5.],
                    [ 5.,  0.,  2.],
                    [ 0.,  6., -3.]])

print(X_train)

[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]


In [ ]:
# Limpieza de datos: normalización.
#nos devuelve un objeto de tipo normalizados
normalizer = preprocessing.MinMaxScaler()
#luego ese normalizador y aplica la función fittransfor, hace dos cosas entrena el normalizador saber porque valor reamplazar y
#Xij Nomralizado
#son dos "funciones" en una misma función fit y transform
X_train_norm = normalizer.fit_transform(X_train)

In [ ]:
# Salida de resultados.
print(X_train_norm)

[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


In [ ]:
# Ejemplo para ver que los resultados son iguales si aplicamos los métodos "fit" y "transform" por separado
X_train_2 = np.copy(X_train)

# Crea un objeto "fitted_normalizer" llamando al método "fit",
# fit solo se aplica en el conjunto de datos de entrenamiento
f = normalizer.fit(X_train)
print(f)
# Aplica el objeto sobre los datos "X_train_2" para obtener "X_train_norm_2"
X_train_norm_2 = f.transform(X_train_2)

# Comprueba si "X_train_norm" y "X_train_norm_2" son iguales
print(np.array_equiv(X_train_norm, X_train_norm_2))

MinMaxScaler()
True


In [ ]:
# Normalizar un nuevo conjunto de datos de test (SOLO HAY QUE APLICAR EL MÉTODO "transform", NO EL "fit")
X_test = np.array([[ 1., -3.,  2.],
                    [ 3.,  0.,  0.],
                    [ 0.,  8., -1.]])

# Normalizar los datos de "X_test"
# ???

In [ ]:
X_train_norm_3 = f.transform(X_test)
print(X_train_norm_3)

[[0.2   0.1   0.625]
 [0.6   0.4   0.375]
 [0.    1.2   0.25 ]]
