<a href="https://colab.research.google.com/github/JorgeZarama/Supervisado/blob/main/Programa4_Ausentes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sklearn.impute import SimpleImputer

In [3]:
# Carga de datos
X_train = [[1,      4],
           [np.nan, 3],
           [7,      8]]

#Cuando es una varable continua se podría ocupar el valor de la media o la mediana para los tema de imputación de valores ausentes
#Cuando es una varable discreta se podría ocupar la moda


In [4]:
# Limpieza de datos: imputación valores ausentes (modelo)
imp = SimpleImputer(strategy='mean') # Utilizamos la estrategia de la media

#Podemos aplicar "fit_transform" sobre 'a', o hacerlo de manera separada con "fit" y "transform"
imputer = imp.fit(X_train)
X_train_clean = imputer.transform(X_train)
print(X_train_clean)

[[1. 4.]
 [4. 3.]
 [7. 8.]]


In [5]:
# Imputación de valores ausentes sobre el conjunto de test
X_test = [[np.nan, 10],
          [6,      np.nan],
          [8,      2]]

# Imputar los datos del conjunto de test
X_test_clean = imputer.transform(X_test)
print(X_test_clean)

[[ 4. 10.]
 [ 6.  5.]
 [ 8.  2.]]


#### EJEMPLO REAL

In [6]:
import pandas as pd

# Cargar dataframe
csv = pd.read_csv('penguins.csv', sep=';')
print(csv.head())

   CulmenLength  CulmenDepth  FlipperLength  BodyMass  Species
0          39.1         18.7          181.0    3750.0        0
1          39.5         17.4          186.0    3800.0        0
2          40.3         18.0          195.0    3250.0        0
3           NaN          NaN            NaN       NaN        0
4          36.7         19.3          193.0    3450.0        0


In [9]:
# Convertir dataframe en numpy array
data = np.array(csv)
print(data)

[[3.910e+01 1.870e+01 1.810e+02 3.750e+03 0.000e+00]
 [3.950e+01 1.740e+01 1.860e+02 3.800e+03 0.000e+00]
 [4.030e+01 1.800e+01 1.950e+02 3.250e+03 0.000e+00]
 ...
 [4.960e+01 1.820e+01 1.930e+02 3.775e+03 2.000e+00]
 [5.080e+01 1.900e+01 2.100e+02 4.100e+03 2.000e+00]
 [5.020e+01 1.870e+01 1.980e+02 3.775e+03 2.000e+00]]


In [8]:
# Comprobar si existen valores ausentes
pos_ausentes = np.unique(np.where(np.isnan(data))[0])
print(pos_ausentes)

[  3 271]


In [10]:
# Definimos imputador con la estrategia de la media
imputer = SimpleImputer(strategy='mean')

# Aplicamos el imputador definido sobre los datos
data_clean = imputer.fit_transform(data)

In [11]:
# Comprobar de nuevo si existen valores ausentes
pos_ausentes = np.unique(np.where(np.isnan(data_clean))[0])
print(pos_ausentes)

[]


In [12]:
# Guardamos el nuevo dataset corregido
df = pd.DataFrame(np.round(data_clean, 2), columns = ["Culmen length","Culmen depth","Flipper length","Body mass","Especies"])
df.to_csv('penguins_clean.csv', sep=';', index=False)