<a href="https://colab.research.google.com/github/JorgeZarama/Supervisado/blob/main/Programa2_Estandarizacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import preprocessing
import numpy as np

In [ ]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [ ]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
# ???
X_train_std = standardizer.fit_transform(X_train)
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [ ]:
X_train_2 = np.array([[ 1., -1.,  2.],
                    [ 2.,  1.,  1.],
                    [ 1.,  1., -1.]])

In [ ]:
# Aplicamos los métodos "fit" y "transform" por separado
# ???
# ???

f = standardizer.fit(X_train)
X_train_std_2 = f.transform(X_train)
print(np.array_equiv(X_train_std, X_train_std_2))

True


In [ ]:
X_train_std_3 = f.transform(X_train_2)
print(X_train_std_3)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  1.22474487  0.53452248]
 [ 0.          1.22474487 -1.06904497]]
